#!/usr/bin/expect -f
set op0 [lindex $argv 0]

set timeout 300
spawn screen -r 
match_max 100000
send -- "module $op0\r"
expect { 
        -exact "Server: Module loaded"                  {}
        -exact "Server: Unable to load module"          {send -- "exit\r" ; expect eof}
        }
send -- "\001C"
send -- "\001d"
expect eof
