#!/usr/bin/expect -f
set option [lindex $argv 0]
set setting [lindex $argv 1 ]
set timeout 1
spawn screen -r 
match_max 100000
send "$option $setting\r"
sleep .1
send -- "\001C"
send -- "\001d"
expect eof
