#!/usr/bin/expect -f
set client [lindex $argv 0]
set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout 2 
spawn screen -r
match_max 100000
send -- "clientinfo $client\r"
expect eof
