#!/usr/bin/expect -f
set slot [lindex $argv 0]
set slotname [lindex $argv 1]
set timeout 300
spawn screen -r
match_max 100000
send -- "forcesave $slot, $slotname\r"
expect -exact "Server: Save complete"
send -- "\001C"
send -- "\001d"
expect eof
