#!/usr/bin/expect -f
set slot [lindex $argv 0]
set slotname [lindex $argv 1]
set timeout 30
spawn screen -r
match_max 100000
send -- "save $slot, $slotname\r"
expect { 
        -exact "Server: Save complete"                  {}
        -exact "Server: Specified slot is in use"       {send -- "\001C" ; send -- "\001d"; expect eof}
        }
send -- "\001C"
send -- "\001d"
expect eof
